In [4]:
import numpy as np

In [26]:
# one dimension
lis = [1,2,3]
tu = (1,2,3)
arr = np.array(lis) #ndim for check dimension
print(arr)

[1 2 3]


In [36]:
#two dimension
arr2 = np.array([[1,2,3],[4,5,6]]) #[[row 1], [row 2], [row 3]]
print(arr2.ndim)

2


In [49]:
#three dimension
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
arr3 = np.array(nested_list)
print(arr3[1][2][0])  #[dept][row][colum]

21


In [62]:
#data type
Darr = np.array([1,2,3,4,5],dtype="int")
Darr.dtype
print(Darr)

[1 2 3 4 5]


In [82]:
#Create Matrix
#---zero
#arr_zero = np.zeros((3,4))

#---one         
#arr_one = np.ones((5,5))

#---#(number,  value)           
#arr_conts = np.full(2,10)

#---Empty arr         
#arr_emp = np.empty((3,4))  

#identity        
print(arr_emp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
